### ISSUE TITLE
Magento CE 1.9?

### ISSUE THREAD

**Issue by phrench** [QVCItalia/magento-configurable-auto-pricing#2]
Does this work with Magento CE 1.9 or is it only for EE?

**Comment by dariodor** [comment]
Same question, after my tests a simple anser: No. The price of configurable products doesn't change.

**Comment by phrench** [comment]
Thanks for posting your findings.

**Comment by alessandroniciforo** [comment]
Hi @dariodor, thanks for contributing.

A user answered himself the same question a while ago saying that he
> forgot to go to the parent product and select the indicated "split" under Prices section

See this [issue](https://github.com/QVCItalia/magento-configurable-auto-pricing/issues/1)

Are you sure the product was setup correctly?

**Comment by phrench** [comment]
@alessandroniciforo: Are you the owner of this repo?

Maybe you can answer the initial question, whther this is supposed to work with CE?

**Comment by crivabene** [comment]
@phrench we never tested it directly against CE, but according to the issue @alessandroniciforo referenced, it works on CE 1.9

**Comment by phrench** [comment]
@crivabene I see. Checked the referenced issue only now. Thanks for clarifying.

**Comment by crivabene** [comment]
@phrench yes, it was used on www.qvc.it until end of July.
