### ISSUE TITLE
Magento 1.9.x currency symbol not showing in windows 7

### ISSUE THREAD

**Issue by supravatweb** [QVCItalia/magento-configurable-auto-pricing#3]
In magento 1.9.x instant, Indian currency symbol is not support. Other then all newer windows version Indian Rupee Symbol is showing perfectly. My query is that why not showing? How to fix it??

 Need help.

**Comment by crivabene** [comment]
supratweb, is your issue with Magento 1.9.x in general, or with the configurable auto pricing extension?

**Comment by supravatweb** [comment]
When I use ₹ instead of Rs from admin->system->Manage Currency-> Symbol. Thats issue is coming.

**Comment by crivabene** [comment]
I understand you are talking about an issue with Magento, and not with this extension.
I suggest you to post it in the Magento Community forums at http://community.magento.com/
