### ISSUE TITLE
Parent price doesn't get set to lowest price found in children

### ISSUE THREAD

**Issue by phrench** [QVCItalia/magento-configurable-auto-pricing#4]
The extension work in my CE 1.9.1.0, except when saving the parent product, the price of the parent product isn't set to the lowest price found in the children.

In the "Super product attributes configuration" the relative price differences are updated, but the parent product price is still the one which was manually set.

According to the usage description this should work. Is this a known bug?

**Comment by alessandroniciforo** [comment]
@phrench good to hear it's mostly working on CE 1.9.1.0

Regarding your issue, there's a configuration in the backend, under the section "Configurable Auto Pricing", labeled as "Parent price from children" that is meant to enable/disable this behavior. Is it set to "Yes"?

As you noticed, there's not a proper explanation of this configuration options in the README at this moment. I'll update it.

**Comment by phrench** [comment]
Wasn't aware there's configuration settings in the backend.
It was set to "No" by default. After enabling it works.

Yes, mentioning the setting in the readme would have helped :)

Thanks for the fast reply!
And also for this great extension.
