### ISSUE TITLE
Automation or cron

### ISSUE THREAD

**Issue by Chowix** [QVCItalia/magento-configurable-auto-pricing#5]
Hello,
is it possible to automate or update all products?
Daily updates product prices. Therefore, I do not see manually update the 4000 products. :)

**Comment by crivabene** [comment]
Hello @Chowix, would you please provide further details about your question?
This module allows you to automatically adjust the settings of configurable products with different pricing per SKU.

**Comment by Chowix** [comment]
Hello @crivabene, The idea is that daily updates product prices. Changing product prices by SKU (simple products). When I update all products, the products configurable do not have the updated prices (0$). I can not sort the products in the catalog because the products configurable have a 0$. Your script is good, but i must save manually all products in Admin->Catalog then I will update the price of the product configurable. Sorry for my English.

**Comment by alessandroniciforo** [comment]
Hi @Chowix, 

quoting from the readme

> Make sure to save the parent product after you have modified the children products prices.

From your comment, it seems like you are already updating the product prices programmatically. This module kicks on every save event of the parent product. You should just make sure to save the parent product after you updated the prices of each child.

Also, take a look at the [configuration](https://github.com/QVCItalia/magento-configurable-auto-pricing#configuration) options, in case you need/don't need to take the base price from the children or in case you want to copy from the children other attributes to the parent.

I hope I answered your question. Let me know if you need anything else.

**Comment by Chowix** [comment]
i write this code

`require 'app/Mage.php';
Mage::app();

$_productCollection1 = Mage::getResourceModel('catalog/product_collection')
	->addAttributeToSelect('*')
	->addAttributeToFilter('type_id','configurable'); 

foreach ($_productCollection1 as $product) {
    echo 'saving product '.$product->getData('sku').PHP_EOL;
    $product->save();
    echo 'saved'.PHP_EOL;
}`

but it does not update the price

**Comment by alessandroniciforo** [comment]
When you run that code are the prices of the children products already updated?
Did you set the attribute "is_split_value" on the parent product?

**Comment by Chowix** [comment]
This option is "yes." I wrote a small script - just turn it on. ~ 500 products at the time of 3-4 minutes.

update_product.php in root folder

```
<?php
	require 'app/Mage.php';


	Mage::app();
	
	$_productCollection = Mage::getResourceModel('catalog/product_collection')
		->addAttributeToSelect('*')
		->addAttributeToFilter('type_id','configurable'); 

	foreach ($_productCollection as $_product) {

		$conf = Mage::getModel('catalog/product_type_configurable')->setProduct($_product);
		$simple_collection = $conf->getUsedProductCollection()->addAttributeToSelect('*')->addFilterByRequiredOptions();
		
		$price = array();
		
		foreach($simple_collection as $simple_product){
			$price[] = $simple_product->getPrice();
		}
		
		$set_price = min($price);
		
		unset($price);
		
		$_product->setPrice($set_price);
		$_product->save();
		
	}
```

**Comment by alessandroniciforo** [comment]
Your code doesn't seem to behave as specified in the "Usage" paragraph of the [README](https://github.com/QVCItalia/magento-configurable-auto-pricing/blob/master/README.md) 
Please read also the "Limitation" paragraph to be sure your use-case doesn't fall into that case.

If you want to leverage this module, you're supposed to:

- Set the individual prices on the children products.
- Set the "Is split value" flag of the parent product, in tab "Prices".
- Make sure to save the parent product after you have modified the children products prices.
